name: test
on: push

jobs:
  lint:
    name: Lint files
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Super-Linter
      uses: docker://ghcr.io/github/super-linter:slim-v4
      env:
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        LOG_LEVEL: NOTICE
        SUPPRESS_POSSUM: true
        VALIDATE_DOCKERFILE: false
        VALIDATE_DOCKERFILE_HADOLINT: false
        VALIDATE_GROOVY: false

    - name: vint
      uses: reviewdog/action-vint@v1.8.0
      with:
        github_token: ${{ secrets.github_token }}
        reporter: github-pr-review
