name: test
on: push

jobs:
  lint:
    name: Lint files
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Super-Linter
      uses: docker://ghcr.io/github/super-linter:slim-v4
      env:
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        LOG_LEVEL: NOTICE
        SUPPRESS_POSSUM: false
        VALIDATE_DOCKERFILE: false
        VALIDATE_DOCKERFILE_HADOLINT: false
