name: test

# yamllint disable-line rule:truthy
on: push

jobs:
  lint:
    name: Lint files
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

    - name: vint
      uses: reviewdog/action-vint@b249164f0c17d7a24aecccea84f2c7e132072731  # v1.17.2
      with:
        github_token: ${{ secrets.github_token }}
        reporter: github-pr-review
