name: test

# yamllint disable-line rule:truthy
on: push

permissions:
  contents: read

jobs:
  lint:
    name: Lint files
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      with:
        persist-credentials: false

    - name: vint
      uses: reviewdog/action-vint@b249164f0c17d7a24aecccea84f2c7e132072731  # v1.17.2
      with:
        github_token: ${{ secrets.github_token }}
        reporter: github-pr-review
